// <auto-generated />
using CarCatalogue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarCatalogue.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20250226112402_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarCatalogue.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://img.freepik.com/free-psd/time-machine-concept-isolated_23-2151874012.jpg?t=st=1740562863~exp=1740566463~hmac=32e8ff462d027d26353018ed39b93ef535d0f147085155321066a981486c58c5&w=1380",
                            Name = "Kasla",
                            Price = 0.0
                        });
                });

            modelBuilder.Entity("CarCatalogue.Models.CarSpec", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "SpecId");

                    b.HasIndex("SpecId");

                    b.ToTable("CarSpecs");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            SpecId = 1
                        },
                        new
                        {
                            CarId = 1,
                            SpecId = 2
                        });
                });

            modelBuilder.Entity("CarCatalogue.Models.Spec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Centralised Voice Control OS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Flying Amphibious"
                        });
                });

            modelBuilder.Entity("CarCatalogue.Models.CarSpec", b =>
                {
                    b.HasOne("CarCatalogue.Models.Car", "Car")
                        .WithMany("CarSpecs")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarCatalogue.Models.Spec", "Spec")
                        .WithMany("CarSpecs")
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("CarCatalogue.Models.Car", b =>
                {
                    b.Navigation("CarSpecs");
                });

            modelBuilder.Entity("CarCatalogue.Models.Spec", b =>
                {
                    b.Navigation("CarSpecs");
                });
#pragma warning restore 612, 618
        }
    }
}
